// Copyright 1998-2014 Epic Games, Inc. All Rights Reserved.

#pragma once

#include "BlueprintCore.generated.h"

UCLASS()
class UBlueprintCore : public UObject
{
	GENERATED_UCLASS_BODY()

	/** Pointer to the skeleton class; this is regenerated any time a member variable or function is added but  
	is usually incomplete (no code or hidden autogenerated variables are added to it) */
	UPROPERTY(nontransactional, transient)
	TSubclassOf<class UObject>  SkeletonGeneratedClass;

	/** Pointer to the 'most recent' fully generated class */
	UPROPERTY(nontransactional)
	TSubclassOf<class UObject>	GeneratedClass;

	/** BackCompat:  Whether or not we need to purge references in this blueprint to the skeleton generated during compile-on-load  */
	UPROPERTY()
	bool bLegacyNeedToPurgeSkelRefs;

private:
	/** BackCompat: Whether or not this blueprint's authoritative CDO data has been migrated from the SkeletonGeneratedClass CDO to the GeneratedClass CDO */
	UPROPERTY()
	bool bLegacyGeneratedClassIsAuthoritative;

public:
	void SetLegacyGeneratedClassIsAuthoritative()
	{
		bLegacyGeneratedClassIsAuthoritative = true;
	}

	bool IsGeneratedClassAuthoritative()
	{
		return bLegacyGeneratedClassIsAuthoritative;
	}

	virtual void Serialize( FArchive& Ar ) OVERRIDE;

	/** Gets asset registry tags */
	virtual void GetAssetRegistryTags(TArray<FAssetRegistryTag>& OutTags) const OVERRIDE;
};