//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools.CrashReporter.CrashReportWebSite.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/CrashReporterFiles/")]
        public string CrashReporterFiles {
            get {
                return ((string)(this["CrashReporterFiles"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/CrashReporterVideos/")]
        public string CrashReporterVideos {
            get {
                return ((string)(this["CrashReporterVideos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/CrashReporterCSV/")]
        public string CrashReporterCSV {
            get {
                return ((string)(this["CrashReporterCSV"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://jira.ol.epicgames.net/rest/api/2")]
        public string JiraDeploymentAddress {
            get {
                return ((string)(this["JiraDeploymentAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\devweb-02\\Sites")]
        public string SitePath {
            get {
                return ((string)(this["SitePath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://hooks.slack.com/services/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")]
        public string SlackWebhookUrl {
            get {
                return ((string)(this["SlackWebhookUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#crashreporterspam")]
        public string SlackChannel {
            get {
                return ((string)(this["SlackChannel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CrashReportWebsite")]
        public string SlackUsername {
            get {
                return ((string)(this["SlackUsername"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":rngesus:")]
        public string SlackEmoji {
            get {
                return ((string)(this["SlackEmoji"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<CrashDescription>\r\n\t<CrashType />\r\n\t<BranchName>//UE4/Release-4.12</BranchName>\r" +
            "\n\t<GameName>UE4-Lenar_3</GameName>\r\n\t<Platform>Win64 [Windows 7 Service Pack 1 6" +
            "4b]</Platform>\r\n\t<EngineMode>Editor</EngineMode>\r\n\t<BuildVersion>4.12.5</BuildVe" +
            "rsion>\r\n\t<BuiltFromCL>3039270</BuiltFromCL>\r\n\t<CommandLine />\r\n\t<BaseDir>C:/Prog" +
            "ram Files (x86)/Epic Games/4.12/Engine/Binaries/Win64/</BaseDir>\r\n\t<Language>zh_" +
            "CN</Language>\r\n\t<SystemLanguage />\r\n\t<UserName>ohmimi</UserName>\r\n\t<MachineGuid>" +
            "A24BAFFA41A33062DF1BCB9A31DDE162</MachineGuid>\r\n\t<EpicAccountId>cc732bdf5c4443f4" +
            "a966a15bd4869c1e</EpicAccountId>\r\n\t<CallStack>UE4Editor_Core!FDebug::OptionallyL" +
            "ogFormattedEnsureMessageReturningFalse() [d:\\build\\++ue4+release-4.12+compile\\sy" +
            "nc\\engine\\source\\runtime\\core\\private\\misc\\outputdevice.cpp:451]</CallStack>\r\n\t<" +
            "CallStack>UE4Editor_Engine!UBlueprint::SetObjectBeingDebugged() [d:\\build\\++ue4+" +
            "release-4.12+compile\\sync\\engine\\source\\runtime\\engine\\private\\blueprint.cpp:685" +
            "]</CallStack>\r\n\t<CallStack>UE4Editor_Engine!UWorld::TransferBlueprintDebugRefere" +
            "nces() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\engine\\pr" +
            "ivate\\world.cpp:1618]</CallStack>\r\n\t<CallStack>UE4Editor_UnrealEd!UEditorEngine:" +
            ":TeardownPlaySession() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\e" +
            "ditor\\unrealed\\private\\playlevel.cpp:642]</CallStack>\r\n\t<CallStack>UE4Editor_Unr" +
            "ealEd!UEditorEngine::EndPlayMap() [d:\\build\\++ue4+release-4.12+compile\\sync\\engi" +
            "ne\\source\\editor\\unrealed\\private\\playlevel.cpp:255]</CallStack>\r\n\t<CallStack>UE" +
            "4Editor_LevelEditor!FLevelViewportLayout::~FLevelViewportLayout() [d:\\build\\++ue" +
            "4+release-4.12+compile\\sync\\engine\\source\\editor\\leveleditor\\private\\levelviewpo" +
            "rtlayout.cpp:145]</CallStack>\r\n\t<CallStack>UE4Editor_LevelEditor!FLevelViewportL" +
            "ayout2x2::`scalar deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_Leve" +
            "lEditor!FLevelViewportTabContent::~FLevelViewportTabContent()</CallStack>\r\n\t<Cal" +
            "lStack>UE4Editor_LevelEditor!SharedPointerInternals::TReferenceControllerWithDel" +
            "eter&lt;FLevelViewportTabContent,SharedPointerInternals::DefaultDeleter&lt;FLeve" +
            "lViewportTabContent&gt; &gt;::DestroyObject() [d:\\build\\++ue4+release-4.12+compi" +
            "le\\sync\\engine\\source\\runtime\\core\\public\\templates\\sharedpointerinternals.h:104" +
            "]</CallStack>\r\n\t<CallStack>UE4Editor_LevelEditor!SViewportsOverlay::~SViewportsO" +
            "verlay()</CallStack>\r\n\t<CallStack>UE4Editor_LevelEditor!SViewportsOverlay::`scal" +
            "ar deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!FSimpleSl" +
            "ot::~FSimpleSlot()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!SCompoundWidget:" +
            ":~SCompoundWidget()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SBorder::`vector de" +
            "leting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!TIndirectArray" +
            "&lt;SOverlay::FOverlaySlot,FDefaultAllocator&gt;::DestructAndFreeItems() [d:\\bui" +
            "ld\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\core\\public\\containers\\" +
            "array.h:3410]</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!SOverlay::~SOverlay()" +
            "</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SOverlay::`scalar deleting destructor\'" +
            "()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!TIndirectArray&lt;SBoxPanel::FSl" +
            "ot,FDefaultAllocator&gt;::DestructAndFreeItems() [d:\\build\\++ue4+release-4.12+co" +
            "mpile\\sync\\engine\\source\\runtime\\core\\public\\containers\\array.h:3410]</CallStack" +
            ">\r\n\t<CallStack>UE4Editor_SlateCore!SBoxPanel::~SBoxPanel()</CallStack>\r\n\t<CallSt" +
            "ack>UE4Editor_Slate!SVerticalBox::`scalar deleting destructor\'()</CallStack>\r\n\t<" +
            "CallStack>UE4Editor_SlateCore!FSimpleSlot::~FSimpleSlot()</CallStack>\r\n\t<CallSta" +
            "ck>UE4Editor_SlateCore!SCompoundWidget::~SCompoundWidget()</CallStack>\r\n\t<CallSt" +
            "ack>UE4Editor_Slate!SDockingTabStack::`vector deleting destructor\'()</CallStack>" +
            "\r\n\t<CallStack>UE4Editor_SlateCore!FSlotBase::~FSlotBase() [d:\\build\\++ue4+releas" +
            "e-4.12+compile\\sync\\engine\\source\\runtime\\slatecore\\private\\slotbase.cpp:34]</Ca" +
            "llStack>\r\n\t<CallStack>UE4Editor_Slate!TIndirectArray&lt;SSplitter::FSlot,FDefaul" +
            "tAllocator&gt;::DestructAndFreeItems() [d:\\build\\++ue4+release-4.12+compile\\sync" +
            "\\engine\\source\\runtime\\core\\public\\containers\\array.h:3410]</CallStack>\r\n\t<CallS" +
            "tack>UE4Editor_Slate!SSplitter::~SSplitter()</CallStack>\r\n\t<CallStack>UE4Editor_" +
            "Slate!SSplitter::`vector deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Edit" +
            "or_SlateCore!FSimpleSlot::~FSimpleSlot()</CallStack>\r\n\t<CallStack>UE4Editor_Slat" +
            "eCore!SCompoundWidget::~SCompoundWidget()</CallStack>\r\n\t<CallStack>UE4Editor_Sla" +
            "te!SDockingSplitter::`vector deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4" +
            "Editor_SlateCore!FSlotBase::~FSlotBase() [d:\\build\\++ue4+release-4.12+compile\\sy" +
            "nc\\engine\\source\\runtime\\slatecore\\private\\slotbase.cpp:34]</CallStack>\r\n\t<CallS" +
            "tack>UE4Editor_Slate!TIndirectArray&lt;SSplitter::FSlot,FDefaultAllocator&gt;::D" +
            "estructAndFreeItems() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\ru" +
            "ntime\\core\\public\\containers\\array.h:3410]</CallStack>\r\n\t<CallStack>UE4Editor_Sl" +
            "ate!SSplitter::~SSplitter()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SSplitter::" +
            "`vector deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!FSim" +
            "pleSlot::~FSimpleSlot()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!SCompoundWi" +
            "dget::~SCompoundWidget()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SDockingSplitt" +
            "er::`vector deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!" +
            "FSlotBase::~FSlotBase() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\" +
            "runtime\\slatecore\\private\\slotbase.cpp:34]</CallStack>\r\n\t<CallStack>UE4Editor_Sl" +
            "ate!TIndirectArray&lt;SSplitter::FSlot,FDefaultAllocator&gt;::DestructAndFreeIte" +
            "ms() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\core\\public" +
            "\\containers\\array.h:3410]</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SSplitter::~S" +
            "Splitter()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SSplitter::`vector deleting " +
            "destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!TIndirectArray&lt;SOv" +
            "erlay::FOverlaySlot,FDefaultAllocator&gt;::DestructAndFreeItems() [d:\\build\\++ue" +
            "4+release-4.12+compile\\sync\\engine\\source\\runtime\\core\\public\\containers\\array.h" +
            ":3410]</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!SOverlay::~SOverlay()</CallS" +
            "tack>\r\n\t<CallStack>UE4Editor_Slate!SOverlay::`scalar deleting destructor\'()</Cal" +
            "lStack>\r\n\t<CallStack>UE4Editor_SlateCore!FSimpleSlot::~FSimpleSlot()</CallStack>" +
            "\r\n\t<CallStack>UE4Editor_SlateCore!SCompoundWidget::~SCompoundWidget()</CallStack" +
            ">\r\n\t<CallStack>UE4Editor_Slate!SDockingArea::`vector deleting destructor\'()</Cal" +
            "lStack>\r\n\t<CallStack>UE4Editor_SlateCore!TIndirectArray&lt;SBoxPanel::FSlot,FDef" +
            "aultAllocator&gt;::DestructAndFreeItems() [d:\\build\\++ue4+release-4.12+compile\\s" +
            "ync\\engine\\source\\runtime\\core\\public\\containers\\array.h:3410]</CallStack>\r\n\t<Ca" +
            "llStack>UE4Editor_SlateCore!SBoxPanel::~SBoxPanel()</CallStack>\r\n\t<CallStack>UE4" +
            "Editor_LevelEditor!SVerticalBox::`scalar deleting destructor\'()</CallStack>\r\n\t<C" +
            "allStack>UE4Editor_SlateCore!FSimpleSlot::~FSimpleSlot()</CallStack>\r\n\t<CallStac" +
            "k>UE4Editor_SlateCore!SCompoundWidget::~SCompoundWidget()</CallStack>\r\n\t<CallSta" +
            "ck>UE4Editor_LevelEditor!SLevelEditor::`scalar deleting destructor\'()</CallStack" +
            ">\r\n\t<CallStack>UE4Editor_SlateCore!FSimpleSlot::~FSimpleSlot()</CallStack>\r\n\t<Ca" +
            "llStack>UE4Editor_SlateCore!SCompoundWidget::~SCompoundWidget()</CallStack>\r\n\t<C" +
            "allStack>UE4Editor_Slate!SBorder::`vector deleting destructor\'()</CallStack>\r\n\t<" +
            "CallStack>UE4Editor_SlateCore!TIndirectArray&lt;SOverlay::FOverlaySlot,FDefaultA" +
            "llocator&gt;::DestructAndFreeItems() [d:\\build\\++ue4+release-4.12+compile\\sync\\e" +
            "ngine\\source\\runtime\\core\\public\\containers\\array.h:3410]</CallStack>\r\n\t<CallSta" +
            "ck>UE4Editor_SlateCore!SOverlay::~SOverlay()</CallStack>\r\n\t<CallStack>UE4Editor_" +
            "Slate!SOverlay::`scalar deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Edito" +
            "r_SlateCore!TIndirectArray&lt;SBoxPanel::FSlot,FDefaultAllocator&gt;::DestructAn" +
            "dFreeItems() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\cor" +
            "e\\public\\containers\\array.h:3410]</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!S" +
            "BoxPanel::~SBoxPanel()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SVerticalBox::`s" +
            "calar deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!FSimpl" +
            "eSlot::~FSimpleSlot()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!SCompoundWidg" +
            "et::~SCompoundWidget()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SDockingTabStack" +
            "::`vector deleting destructor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!FS" +
            "lotBase::~FSlotBase() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\ru" +
            "ntime\\slatecore\\private\\slotbase.cpp:34]</CallStack>\r\n\t<CallStack>UE4Editor_Slat" +
            "e!TIndirectArray&lt;SSplitter::FSlot,FDefaultAllocator&gt;::DestructAndFreeItems" +
            "() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\core\\public\\c" +
            "ontainers\\array.h:3410]</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SSplitter::~SSp" +
            "litter()</CallStack>\r\n\t<CallStack>UE4Editor_Slate!SSplitter::`vector deleting de" +
            "structor\'()</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!TIndirectArray&lt;SOver" +
            "lay::FOverlaySlot,FDefaultAllocator&gt;::DestructAndFreeItems() [d:\\build\\++ue4+" +
            "release-4.12+compile\\sync\\engine\\source\\runtime\\core\\public\\containers\\array.h:3" +
            "410]</CallStack>\r\n\t<CallStack>UE4Editor_SlateCore!SOverlay::~SOverlay()</CallSta" +
            "ck>\r\n\t<CallStack>UE4Editor_Slate!SOverlay::`scalar deleting destructor\'()</CallS" +
            "tack>\r\n\t<CallStack>UE4Editor_SlateCore!TArray&lt;FArrangedWidget,TInlineAllocato" +
            "r&lt;16,FDefaultAllocator&gt; &gt;::~TArray&lt;FArrangedWidget,TInlineAllocator&" +
            "lt;16,FDefaultAllocator&gt; &gt;() [d:\\build\\++ue4+release-4.12+compile\\sync\\eng" +
            "ine\\source\\runtime\\core\\public\\containers\\array.h:723]</CallStack>\r\n\t<CallStack>" +
            "UE4Editor_Slate!FSlateApplication::RoutePointerUpEvent() [d:\\build\\++ue4+release" +
            "-4.12+compile\\sync\\engine\\source\\runtime\\slate\\private\\framework\\application\\sla" +
            "teapplication.cpp:4667]</CallStack>\r\n\t<CallStack>UE4Editor_Slate!FSlateApplicati" +
            "on::ProcessMouseButtonUpEvent() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine" +
            "\\source\\runtime\\slate\\private\\framework\\application\\slateapplication.cpp:5041]</" +
            "CallStack>\r\n\t<CallStack>UE4Editor_Slate!FSlateApplication::OnMouseUp() [d:\\build" +
            "\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\slate\\private\\framework\\a" +
            "pplication\\slateapplication.cpp:5021]</CallStack>\r\n\t<CallStack>UE4Editor_Core!FW" +
            "indowsApplication::ProcessDeferredMessage() [d:\\build\\++ue4+release-4.12+compile" +
            "\\sync\\engine\\source\\runtime\\core\\private\\windows\\windowsapplication.cpp:1510]</C" +
            "allStack>\r\n\t<CallStack>UE4Editor_Core!FWindowsApplication::DeferMessage() [d:\\bu" +
            "ild\\++ue4+release-4.12+compile\\sync\\engine\\source\\runtime\\core\\private\\windows\\w" +
            "indowsapplication.cpp:1850]</CallStack>\r\n\t<CallStack>UE4Editor_Core!FWindowsAppl" +
            "ication::ProcessMessage() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\sourc" +
            "e\\runtime\\core\\private\\windows\\windowsapplication.cpp:745]</CallStack>\r\n\t<CallSt" +
            "ack>UE4Editor_Core!FWindowsApplication::AppWndProc() [d:\\build\\++ue4+release-4.1" +
            "2+compile\\sync\\engine\\source\\runtime\\core\\private\\windows\\windowsapplication.cpp" +
            ":667]</CallStack>\r\n\t<CallStack>user32!UserCallWinProcCheckWow()</CallStack>\r\n\t<C" +
            "allStack>user32!DispatchMessageWorker()</CallStack>\r\n\t<CallStack>UE4Editor_Core!" +
            "FWindowsPlatformMisc::PumpMessages() [d:\\build\\++ue4+release-4.12+compile\\sync\\e" +
            "ngine\\source\\runtime\\core\\private\\windows\\windowsplatformmisc.cpp:903]</CallStac" +
            "k>\r\n\t<CallStack>UE4Editor!FEngineLoop::Tick() [d:\\build\\++ue4+release-4.12+compi" +
            "le\\sync\\engine\\source\\runtime\\launch\\private\\launchengineloop.cpp:2729]</CallSta" +
            "ck>\r\n\t<CallStack>UE4Editor!GuardedMain() [d:\\build\\++ue4+release-4.12+compile\\sy" +
            "nc\\engine\\source\\runtime\\launch\\private\\launch.cpp:148]</CallStack>\r\n\t<CallStack" +
            ">UE4Editor!GuardedMainWrapper() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine" +
            "\\source\\runtime\\launch\\private\\windows\\launchwindows.cpp:126]</CallStack>\r\n\t<Cal" +
            "lStack>UE4Editor!WinMain() [d:\\build\\++ue4+release-4.12+compile\\sync\\engine\\sour" +
            "ce\\runtime\\launch\\private\\windows\\launchwindows.cpp:200]</CallStack>\r\n\t<CallStac" +
            "k>UE4Editor!__scrt_common_main_seh() [f:\\dd\\vctools\\crt\\vcstartup\\src\\startup\\ex" +
            "e_common.inl:264]</CallStack>\r\n\t<CallStack>kernel32!BaseThreadInitThunk()</CallS" +
            "tack>\r\n\t<CallStack>ntdll!RtlUserThreadStart()</CallStack>\r\n\t<SourceContext>  670" +
            "       \t{</SourceContext>\r\n\t<SourceContext>  671       \t\tif (OldObject == NewObj" +
            "ect)</SourceContext>\r\n\t<SourceContext>  672       \t\t{</SourceContext>\r\n\t<SourceC" +
            "ontext>  673       \t\t\t// Nothing changed</SourceContext>\r\n\t<SourceContext>  674 " +
            "      \t\t\treturn;</SourceContext>\r\n\t<SourceContext>  675       \t\t}</SourceContext" +
            ">\r\n\t<SourceContext>  676       </SourceContext>\r\n\t<SourceContext>  677       \t\tD" +
            "ebuggingWorldRegistrationHelper(OldObject, NULL);</SourceContext>\r\n\t<SourceConte" +
            "xt>  678       \t}</SourceContext>\r\n\t<SourceContext>  679       </SourceContext>\r" +
            "\n\t<SourceContext>  680       \t// Note that we allow macro Blueprints to bypass t" +
            "his check</SourceContext>\r\n\t<SourceContext>  681       \tif ((NewObject != NULL) " +
            "&amp;&amp; !GCompilingBlueprint &amp;&amp; BlueprintType != BPTYPE_MacroLibrary)" +
            "</SourceContext>\r\n\t<SourceContext>  682       \t{</SourceContext>\r\n\t<SourceContex" +
            "t>  683       \t\t// You can only debug instances of this!</SourceContext>\r\n\t<Sour" +
            "ceContext>  684 ***** \t\tif (!ensureMsgf(</SourceContext>\r\n\t<SourceContext>  685 " +
            "      \t\t\t\tNewObject-&gt;IsA(this-&gt;GeneratedClass), </SourceContext>\r\n\t<Source" +
            "Context>  686       \t\t\t\tTEXT(\"Type mismatch: Expected %s, Found %s\"), </SourceCo" +
            "ntext>\r\n\t<SourceContext>  687       \t\t\t\tthis-&gt;GeneratedClass ? *(this-&gt;Gen" +
            "eratedClass-&gt;GetName()) : TEXT(\"NULL\"), </SourceContext>\r\n\t<SourceContext>  6" +
            "88       \t\t\t\tNewObject-&gt;GetClass() ? *(this-&gt;GetClass()-&gt;GetName()) : T" +
            "EXT(\"NULL\")))</SourceContext>\r\n\t<SourceContext>  689       \t\t{</SourceContext>\r\n" +
            "\t<SourceContext>  690       \t\t\tNewObject = NULL;</SourceContext>\r\n\t<SourceContex" +
            "t>  691       \t\t}</SourceContext>\r\n\t<SourceContext>  692       \t}</SourceContext" +
            ">\r\n\t<SourceContext>  693       </SourceContext>\r\n\t<SourceContext>  694       \t//" +
            " Update the current object being debugged</SourceContext>\r\n\t<SourceContext>  695" +
            "       \tCurrentObjectBeingDebugged = NewObject;</SourceContext>\r\n\t<SourceContext" +
            ">  696       </SourceContext>\r\n\t<SourceContext>  697       \t// Register the new " +
            "object</SourceContext>\r\n\t<SourceContext>  698       \tif (NewObject != NULL)</Sou" +
            "rceContext>\r\n\t<SourceContext>  699       \t{</SourceContext>\r\n\t<UserDescription>S" +
            "ent in the unattended mode</UserDescription>\r\n\t<UserActivityHint />\r\n\t<ErrorMess" +
            "age>Ensure condition failed: NewObject-&gt;IsA(this-&gt;GeneratedClass) [File:D:" +
            "\\Build\\++UE4+Release-4.12+Compile\\Sync\\Engine\\Source\\Runtime\\Engine\\Private\\Blue" +
            "print.cpp] [Line: 689] </ErrorMessage>\r\n\t<ErrorMessage>Type mismatch: Expected U" +
            "ntitled_C, Found LevelScriptBlueprint</ErrorMessage>\r\n\t<CrashGUID>UE4CC-Windows-" +
            "7188BC094DE45EE1A7D39EBF6FB434F5_0000</CrashGUID>\r\n\t<TimeofCrash>2016-07-13T14:5" +
            "8:43.402875Z</TimeofCrash>\r\n\t<bHasMiniDump>true</bHasMiniDump>\r\n\t<bHasLog>true</" +
            "bHasLog>\r\n\t<bHasDiags>false</bHasDiags>\r\n\t<bHasWERData>false</bHasWERData>\r\n\t<bH" +
            "asVideo>false</bHasVideo>\r\n\t<bAllowToBeContacted>true</bAllowToBeContacted>\r\n</C" +
            "rashDescription>")]
        public string TestXML {
            get {
                return ((string)(this["TestXML"]));
            }
        }
    }
}
