// Copyright 1998-2015 Epic Games, Inc. All Rights Reserved.

#pragma once
#include "NavPathObserverInterface.generated.h"

UINTERFACE(MinimalAPI, meta=(CannotImplementInterfaceInBlueprint))
class UNavPathObserverInterface : public UInterface
{
	GENERATED_BODY()
public:
	ENGINE_API UNavPathObserverInterface(const FObjectInitializer& ObjectInitializer = FObjectInitializer::Get());
};

class INavPathObserverInterface
{
	GENERATED_BODY()
public:

	/** 
	 *	Called on Navigation Agent when given PathGenerator updated it's path.
	 */
	virtual void OnPathUpdated(class INavigationPathGenerator* PathGenerator) PURE_VIRTUAL(INavPathObserverInterface::OnPathUpdated,);

	/** 
	 *	Called when path generated by PathGenerator becomes invalid
	 */
	virtual void OnPathInvalid(class INavigationPathGenerator* PathGenerator) PURE_VIRTUAL(INavPathObserverInterface::OnPathInvalid,);

	/** 
	 *	Called when path generation by PathGenerator fails
	 */
	virtual void OnPathFailed(class INavigationPathGenerator* PathGenerator) PURE_VIRTUAL(INavPathObserverInterface::OnPathInvalid,);

};
