// Copyright 1998-2018 Epic Games, Inc. All Rights Reserved.

/*=============================================================================
	VulkanCommon.usf: Common Vulkan shader code
=============================================================================*/

// Update this GUID to improve shader recompilation for Vulkan only shaders
// GUID = {792BDC0A-A4A8-402F-8752-3F9F642A03C3}
// Glslang 1.0.65.1

#pragma once
